sudo: required

language: node_js
node_js:
  - "lts/*"

services:
  - docker

before_install:
  - docker pull ubuntu:16.04
  - docker run ubuntu:16.04 grep -v '^#' /etc/apt/sources.list
  - docker ps -a

install:
  - npm install
  - npm install -g codecov
  # - npm install --production

script:
  - npm run build
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
