sudo: required

language: node_js
node_js:
  - "lts/*"

cache: npm

services:
  - docker

before_install:
  - docker pull ubuntu:16.04
  - docker run ubuntu:16.04 grep -v '^#' /etc/apt/sources.list
  - docker ps -a

install:
  # - npm install
  # - npm install --production
  - npm install -g codecov
  - npm install -D nyc

script:
  - npm run coverage

after_success:
  - npm run report-coverage
